"""Add restaurant_id to orders

Revision ID: 20fd7bea8e19
Revises: f97cbe62a6eb
Create Date: 2023-09-14 13:04:39.960219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fd7bea8e19'
down_revision = 'f97cbe62a6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_orders_restaurant_id', 'restaurants', ['restaurant_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_restaurant_id', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
